### ISSUE TITLE
Bad package version in Nuget

### ISSUE THREAD

**Issue by gkinsman** [G-Research/consuldotnet#112]
Hi there!

It looks like the [latest package](https://www.nuget.org/packages/Consul/1.6.10.2) that was uploaded to nuget 13 days ago breaks nuget installation/resolution as it has a file version number of 0.0.0.0.

The assembly has a full name of `Consul, Version=0.0.0.0, Culture=neutral, PublicKeyToken=20a6ad9a81df1d95`.

1.6.10.2 at the top, 1.6.10.1 at the bottom
![image](https://user-images.githubusercontent.com/130231/127314409-45aac84b-8ab8-4827-8c19-c64b79183026.png)

Note that version `1.6.10.1` has a file version of `1.6.1.1` which appears to be the last stable release in Nuget.

I'd suggest perhaps de-listing these packages so that people who depend on them don't break when upgrading.

Thanks!

**Comment by mfkl** [comment]
1.6.10.3 is live with the fix, @gkinsman.

**Comment by gkinsman** [comment]
Thank you! 💯
