### ISSUE TITLE
Registering a service in a namespace

### ISSUE THREAD

**Issue by ledjon-behluli** [G-Research/consuldotnet#117]
Curious to know if there is any plan to support namespaces in Consul.NET ?
The namespaces functionality is available only in Consul Enterprise version 1.7.0 and later.

**Comment by mfkl** [comment]
I don't see why not, anything from the Consul API should be considered. Would you like to try contribute a PR for this?

**Comment by ledjon-behluli** [comment]
Sure! What's the best way to go about it? 
Should I fork branch development or master?

**Comment by mfkl** [comment]
`master`, the develop branch is not used, we should remove it.

**Comment by ledjon-behluli** [comment]
Got it!

**Comment by winstxnhdw** [comment]
@marcin-krystianc We can close this issue now.

**Comment by ledjon-behluli** [comment]
Yeah
