### ISSUE TITLE
Add ASP.NET Core integration

### ISSUE THREAD

**Issue by sergeyshaykhullin** [G-Research/consuldotnet#15]
- Add IServiceCollection extensions for registering client
- Add IHostedService or IApplicationBuilder extensions for service register/deregister

**Comment by jgiannuzzi** [comment]
Thanks for opening this issue, @sergeyshaykhullin, and sorry for the late response!

Having these extensions could be very useful indeed.
As they depend on ASP.Net Core, we think it should not be implemented in the main library, but rather in another namespace (i.e. `Consul.AspNetCore.Registration`), published as a separate NuGet package.

PRs are welcome, and if anyone wants to work on this, please comment here!

**Comment by sergeyshaykhullin** [comment]
https://github.com/G-Research/consuldotnet/pull/17
