### ISSUE TITLE
Registration with health checks... how do you provide one for gRPC connections?

### ISSUE THREAD

**Issue by dealproc** [G-Research/consuldotnet#153]
According to the [Consul Documentation](https://www.consul.io/docs/discovery/checks), you are able to register for a health check on a gRPC endpoint.  In the present dotnet api, I do not see a similar object model that would allow such a registration.  Is there something I've missed, or does the client object model need a little TLC to configure multiple type(s) of checkpoints, inclusive of the h2c and gRPC health checks?

**Comment by marcin-krystianc** [comment]
There is a way to register gRPC check (see https://github.com/G-Research/consuldotnet/blob/master/Consul/Agent.cs#L273-L277) , but there is nothing in the library that would allow implementing an endpoint for it. 
Regarding the h2c checks - it is not possible to register them at the moment.

**Comment by dealproc** [comment]
Right.  I noticed that, i believe, and had not updated my query.  Sorry about the confusion @marcin-krystianc .
