### ISSUE TITLE
Wrong type

### ISSUE THREAD

**Issue by Bergiu** [G-Research/consuldotnet#156]
https://github.com/G-Research/consuldotnet/blob/40159228a4a2f15284e6eaa6e386dad0738066f5/Consul/Catalog.cs#L53

I think this should be IDictionary instead of Dictionary. Same for the lines: 34 and 61.

**Comment by mfkl** [comment]
Sure, I guess this is a reasonable change. Are you currently blocked by this though?

Feel free to send a PR!

**Comment by marcin-krystianc** [comment]
Whenever we accept any changes like this, we need to consider its binary compatibility.
I think here, the change would be binary incompatible. So on one hand I get the argument that we shouldn't use concrete types on our public interfaces, but on the other hand I think we should just prioritise binary compatibility.

**Comment by Bergiu** [comment]
There are also other occurrences in properties:
 - https://github.com/G-Research/consuldotnet/blob/master/Consul/Agent.cs#L152
 - https://github.com/G-Research/consuldotnet/blob/master/Consul/Agent.cs#L255
 - https://github.com/G-Research/consuldotnet/blob/master/Consul/AuthMethod.cs#L37
 - https://github.com/G-Research/consuldotnet/blob/master/Consul/Client_Request.cs#L54
 - https://github.com/G-Research/consuldotnet/blob/master/Consul/Semaphore.cs#L223
 - https://github.com/G-Research/consuldotnet/blob/master/Consul/Utilities/Extensions.cs#L35
 
And as types in functions:
- https://github.com/G-Research/consuldotnet/blob/master/Consul/Agent.cs#L328
- https://github.com/G-Research/consuldotnet/blob/master/Consul/Agent.cs#L330
- https://github.com/G-Research/consuldotnet/blob/master/Consul/AuthMethod.cs#L54
- https://github.com/G-Research/consuldotnet/blob/master/Consul/AuthMethod.cs#L59
- https://github.com/G-Research/consuldotnet/blob/master/Consul/Client_Request.cs#L80

And in interfaces:
- https://github.com/G-Research/consuldotnet/blob/master/Consul/Interfaces/IAgentEndpoint.cs#L52
- https://github.com/G-Research/consuldotnet/blob/master/Consul/Interfaces/IAgentEndpoint.cs#L53

**Comment by Bergiu** [comment]
I've made two branches: "master" that contains the changes only in Catalog.cs, and "more" that contains all changes.

please let me know if i should make a pr from any of those branches.

**Comment by marcin-krystianc** [comment]
> unfortunately i don't know what is meant by binary compatibility.

By binary compatibility I mean the compatibility when at runtime an assembly references different version of an assembly than was used to compile that particular assembly. It is possible that some library can be compiled against `Consul 1.6.10.7`, but at runtime it will be using higher version (e.g. `Consul 1.6.10.8`). If the newer version is not binary compatible with older version, we will get runtime errors like this one:
```
Unhandled exception. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Consul.QueryResult`1<System.Collections.Generic.Dictionary`2<System.String,System.String[]>>> Consul.ICatalogEndpoint.Services(System.Threading.CancellationToken)'.
   at ConsulTesting.Program.Main()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ConsulTesting.Program.Main()
   at ConsulTesting.Program.<Main>()
```

In small solutions it is probably not an issue, as all projects are going to be compiled against the same version. Unfortunately, the larger the particular solution is, the more likely some projects or NuGet packages will use older version of Consul - and it will lead to fatal errors at runtime.
