### ISSUE TITLE
Asp.Net Core 3.1 on Windows

### ISSUE THREAD

**Issue by ssenart** [G-Research/consuldotnet#16]
Hello,

I did not manage to make Consul.Net library work with .NET Core 3.1 on Windows.

I always face a "Host not found" error while trying to connect to the agent. I tried with a dummy program and with all test unit tests => same result.

It works fine with .NET Core 2.1 and 2.2 in Windows.

I have seen that you have tested .NET Core 3.1 on Linux. Do you confirm the issue on Windows ?

Thanks for your help,
Stephane

**Comment by mfkl** [comment]
Hi,

Can you share a minimal [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) please?

**Comment by ssenart** [comment]
The program below hangs at "put" command until a timeout :    

System.AggregateException: 'One or more errors occurred. (Unexpected response, status code ServiceUnavailable: <HTML><HEAD>
<TITLE>Network Error</TITLE>
</HEAD>
<BODY>
<FONT face="Helvetica">
<big><strong></strong></big><BR>
</FONT>
<blockquote>
<TABLE border=0 cellPadding=1 width="80%">
<TR><TD>
<FONT face="Helvetica">
<big>Network Error (tcp_error)</big>
<BR>
<BR>
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
A communication error occurred: "Operation timed out"
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica">
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
</FONT>
</TD></TR>
<TR><TD>
<FONT face="Helvetica" SIZE=2>
<BR>
For assistance, contact your network support team.
</FONT>
</TD></TR>
</TABLE>
</blockquote>
</FONT>
</BODY></HTML>
)'


class Program
    {
        public static async Task<string> HelloConsul()
        {
            using (var client = new ConsulClient())
            {
                var putPair = new KVPair("hello")
                {
                    Value = Encoding.UTF8.GetBytes("Hello Consul")
                };

                var putAttempt = await client.KV.Put(putPair);

                if (putAttempt.Response)
                {
                    var getPair = await client.KV.Get("hello");
                    return Encoding.UTF8.GetString(getPair.Response.Value, 0,
                        getPair.Response.Value.Length);
                }
                return "";
            }
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Console.WriteLine(HelloConsul().Result);
        }
    }

The problem occurs only on my professional laptop. It does not on my private one.
It tried to remove all .NET SDK and runtime and reinstall the minimum via Visual Studio installers. But it does not fix. Since it works with .NET 2.1, I exclude security software that might have blocked the connection.

I know that Consul.Net is not the cause. It is between my laptop configuration and some .NET Core 3.1 specifics, but what ?

**Comment by jgiannuzzi** [comment]
Hi @ssenart, thanks for your report.

In our CI pipeline, we do run all the unit tests on .NET Framework 4.6.1, .NET Core 2.0, and .NET Core 3.1 on Windows. We also run them on .NET Core 3.1 on Linux and macOS.

I tested your program with .NET Core 3.1 on Windows and it worked fine.

Could you please help clarify a few things?
* The program in your previous comment is a console application, not an ASP.NET application, right?
* When you run the same program on the same machine but with .NET Core 2.1, does it work? Or does it work with .NET 2.1 on a different machine?
* When you run the same program on a different machine with .NET Core 3.1, does it work?
* Are you running a Consul agent on the same machine where the program is running? If so, can you access it with `curl http://127.0.0.1:8500/v1/status/leader` from a PowerShell prompt?

**Comment by ssenart** [comment]
Hi and thanks for your time.

I have found the cause. All HTTP requests are going through the company proxy server.

Even localhost or 127.0.0.1 requests. Obviously, the proxy is unable to DNS resolve localhost or 127.0.0.1, hence the error message I had.

To solve this, I set the environment variable NO_PROXY=localhost,127.0.0.1.

The fact that the behaviour changed between Core 2.x and Core 3.x led me to many investigation directions except thinking of proxy !

Note that CURL command line tool has the same behaviour as Core 3.x.

Thanks again for your time and you can close the issue which is not.
Stephane
