### ISSUE TITLE
How to delete all keys?

### ISSUE THREAD

**Issue by christopher7694** [G-Research/consuldotnet#169]
Passing in an empty prefix throws an exception.
What is the right way to do this?

**Comment by mfkl** [comment]
https://github.com/G-Research/consuldotnet/blob/269b5bdbd5efeb83d9728ee047668239fa63ebe0/Consul/KV.cs#L354-L362

Is that what you're looking for?

**Comment by christopher7694** [comment]
Thanks for the reply!

That call goes to here:
https://github.com/G-Research/consuldotnet/blob/269b5bdbd5efeb83d9728ee047668239fa63ebe0/Consul/KV.cs#L370-L376

which calls: 
https://github.com/G-Research/consuldotnet/blob/269b5bdbd5efeb83d9728ee047668239fa63ebe0/Consul/KV.cs#L372

which in turn calls:
https://github.com/G-Research/consuldotnet/blob/269b5bdbd5efeb83d9728ee047668239fa63ebe0/Consul/KV.cs#L56-L67

When calling List() I am able to pass in "" for prefix to get all the entries and assumed (which could be the problem!) that passing "" into DeleteTree would "delete all", instead it throws an exception as shown above.

Is there another option (other than calling List and deleting one by one?) or is this a bug or perhaps an intentional restriction or something else?

**Comment by mfkl** [comment]
I don't see a way to drop all the keys without specifying a prefix from the docs https://www.consul.io/commands/kv/delete

How would you achieve this with Consul CLI?

**Comment by christopher7694** [comment]
I don't see a way either. Ok. I'll use the workaround for now of getting all the keys and deleting them one by one.

Thanks!
