### ISSUE TITLE
[CI] Fix deprecation warnings

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/consuldotnet#172]
We are getting quite a few deprecation warnings lately, and some of them even result in actual failures: https://github.com/G-Research/consuldotnet/actions/runs/3294480092.

This should be fixed by updating most actions to their latest version.

We should also consider using Dependabot just for actions.

**Comment by mfkl** [comment]
Think the warnings are gone now thanks to dependabot PRs.
