### ISSUE TITLE
Is the class ConsulClient thread safe?

### ISSUE THREAD

**Issue by pablonardone** [G-Research/consuldotnet#173]
I'm not sure if this is the correct place for this question, if it is not I apologize in advance.

I did not find any documentation about the thread safety of ClientConsul class.
Can we have only one instance of ClientConsul and share this instance between multiple tasks querying and writing concurrently to the KV store, or should create a new instance for every operation whith the KV store?.

Thank you.

**Comment by marcin-krystianc** [comment]
> I did not find any documentation about the thread safety of ClientConsul class. Can we have only one instance of ClientConsul and share this instance between multiple tasks querying and writing concurrently to the KV store, or should create a new instance for every operation whith the KV store?.
> 
> Thank you.

Hi @pablonardone,

the `ConsulClient` class is thread safe so it is ok to use it concurrently from multiple threads. Thanks for raising this issue, I'll look into improving the documentation.
