### ISSUE TITLE
Cannot create an associated check for a service with custom check id

### ISSUE THREAD

**Issue by newpma** [G-Research/consuldotnet#184]
Code snippet similar to the following:
```c#
var check = new AgentServiceCheck
{
    ID = id,
    Name = checkName,
    HTTP = healthCheckEndpoint
    Interval = healthCheckInterval,
    Timeout = healthCheck.Timeout
};
var service = new AgentServiceRegistration
{
    ID = serviceId,
    Name = name,
    Address = address,
    Port = port,
    Checks = new AgentServiceCheck[] { check }
};
Consul.Agent.ServiceRegister(service).GetAwaiter().GetResult();
```
raises exception with message: 'BadRequest: Request decode failed: json: unknown field "ID"'

According to [consul documentation](https://developer.hashicorp.com/consul/api-docs/agent/service#checks) custom check id can be provided with `CheckID` attribute which does not exist in class `AgentServiceCheck`: 
https://github.com/G-Research/consuldotnet/blob/4f16eff266710288e3282b416bb29b75a6fb8b3b/Consul/Agent.cs#L215
Of course workaround using something like this is possible:
```c#
public class AgentServiceCheckWhichSolvesIssueUnknownFieldId : AgentServiceCheck
{
    [JsonProperty("CheckID")]
    public string CheckId { get; set; }
}
```
but I hope there is more correct solution.

**Comment by mfkl** [comment]
Could you use `AgentCheck` instead? https://github.com/G-Research/consuldotnet/blob/1902b83246f4f72902d2d7b0c82049c28df617ef/Consul/Agent.cs#L115 

or `HealthCheck`? https://github.com/G-Research/consuldotnet/blob/de686e40be7fe91cba010fe9cd8644f2d2ff9adf/Consul/Health.cs#L107

**Comment by newpma** [comment]
Thanks for your answer.

As far as I know, I couldn't.
I want to create service and its corresponding checks by single http request. As I understand, to do that I should use `AgentServiceRegistration` class and attribute `Checks` which is array of __`AgentServiceCheck`__.

Please correct me If I'm wrong.

**Comment by marcin-krystianc** [comment]
It seems to be a mistake in the documentation (https://developer.hashicorp.com/consul/api-docs/agent/check#json-request-body-schema), as the documentation suggests that the correct field name (when creating the check)  is `ID`.
I think that we should add a new field `CheckId` to the `AgentServiceCheck` class and mark the `ID` field as deprecated. We also need to add a test that uses the `CheckId` field so we avoid such problem in the future.

**Comment by marcin-krystianc** [comment]
@newpma Version [1.6.10.8](https://www.nuget.org/packages/Consul/1.6.10.8) which includes a fix for this issue got released.

**Comment by newpma** [comment]
Thanks a lot!
