### ISSUE TITLE
[Bug]: ServiceRegister does not pass WriteOptions to PutRequest, resulting in missing token and datacenter

### ISSUE THREAD

**Issue by andreiZi** [G-Research/consuldotnet#208]
### Describe the bug

When using the `ServiceRegister` method in the `Consul.NET` library, the `WriteOptions` are not passed to the `PutRequest`. As a result, the token and datacenter information are not included in the request, leading to potential issues with authentication and handling requests in the correct datacenter.

### Example Configuration

![image](https://user-images.githubusercontent.com/53220480/226773283-286c8de3-71ff-469a-8278-07506d840f95.png)

### Output

Because of the described behavior, `PutRequest.Options` has no token and no datacenter provided.

![image](https://user-images.githubusercontent.com/53220480/226773631-22fa4dd6-ce6d-40ad-9996-2d15f6f13d17.png)

However, the configuration appears to be correct.

![image](https://user-images.githubusercontent.com/53220480/226773887-4d0b0a01-2374-4fcb-82b7-9cd39f77ad4c.png)

### Steps To Reproduce

1. Create a `ConsulClient` instance with a valid token and datacenter configuration.
2. Register a service using the `ServiceRegister method.
3. Observe that the token and datacenter are not included in the request sent to the Consul agent.

### Expected behavior

The `ServiceRegister` method should pass the `WriteOptions` containing the token and datacenter information to the `PutRequest, so that they are included in the request sent to the Consul agent.

### Environment

- OS: Linux, Mac
- Consul Version: 1.14.2
- consultdotnet Version: 1.6.10.8

### Proposed Solution

To address the issue, the `ServiceRegister` method in the `Consul.NET` library can be modified to pass the `WriteOptions` from the client's configuration.

```csharp
public Task<WriteResult> ServiceRegister(
    AgentServiceRegistration service,
    bool replaceExistingChecks,
    CancellationToken ct = default (CancellationToken))
{
    PutRequest<AgentServiceRegistration> putRequest = this._client.Put<AgentServiceRegistration>("/v1/agent/service/register", service, this._client.Config.WriteOptions);
    if (replaceExistingChecks)
        putRequest.Params["replace-existing-checks"] = "true";
    return putRequest.Execute(ct);
}
```

### Current Workaround:

A workaround for the issue is to create a subclass of the `ConsulClient` and create a new `CustomConsulClient`. This workaround depends on Consul ACL and policy configuration.

```csharp
using System.Reflection;
using Consul;

namespace BuildingBlocks.Common.Subclasses;

public class CustomConsulClient : ConsulClient
{
    public CustomConsulClient(ConsulClientConfiguration config, HttpClient client)
        : base(config, client)
    {
    }

    public new Task<WriteResult> ServiceRegister(
        AgentServiceRegistration service,
        bool replaceExistingChecks = false,
        CancellationToken ct = default)
    {
        var putMethod = GetType()
            .GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)
            .Where(x => x.Name == "Put")
            .ToList()[0];

        // Create a generic version of the Put method for AgentServiceRegistration
        var putGenericMethod = putMethod.MakeGenericMethod(typeof(AgentServiceRegistration));

        var writeOptions = new WriteOptions { Token = Config.Token, Datacenter = Config.Datacenter };

        // Call the internal Put<TIn> method with the appropriate parameters
        var putRequest = (PutRequest<AgentServiceRegistration>)putGenericMethod.Invoke(this, new object[] { "/v1/agent/service/register", service, writeOptions });

        return putRequest.Execute(ct);
    }
}
```

To use the `CustomConsulClient`, replace `ConsulClient` with `CustomConsulClient as shown below:

```csharp
var consulClient = new CustomConsulClient(consulConfig,httpClient);
consulClient.ServiceRegister(serviceRegistration).Wait();
```
instead of:
```csharp
var consulClient = new ConsulClient(consulConfig,httpClient);
consulClient.Agent.ServiceRegister(serviceRegistration).Wait();
```

**Comment by marcin-krystianc** [comment]
Hi @andreiZi,

thank you for your detailed report.
I tried to follow your steps to reproduce the issue, but I don't think the problem you are describing exists:
- The token value is in fact applied via `DefaultRequestHeaders`, see https://github.com/G-Research/consuldotnet/blob/dea040dba349037a68837e483f5e74602a232b05/Consul/Client.cs#L583-L590
- The `dc` is applied automatically for every `ConsulRequest` -> https://github.com/G-Research/consuldotnet/blob/dea040dba349037a68837e483f5e74602a232b05/Consul/Client_Request.cs#L67-L70

Can you confirm your reproduction steps and check whether `token` and `dc` is set by the linked code?
