### ISSUE TITLE
Support for injecting HttpClient in a non-obsolete constructor

### ISSUE THREAD

**Issue by Salgat** [G-Research/consuldotnet#24]
As of now ConsulClient allows for injecting an HttpClient using an [Obsolete] constructor ([here](https://github.com/G-Research/consuldotnet/blob/master/Consul/Client.cs#L446)). This project should remove this [Obsolete] attribute until an alternative way to inject HttpClient is provided as a migration path (my suggestion is sticking with the current constructor or just a Func\<HttpClient\>). As of now the non-obsolete constructors carry the issue that they internally manage an HttpClient, which means that you either dispose ConsulClient and risk socket exhaustion, or you use a singleton ConsulClient and risk dealing with a stale DNS (see [here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests)). My personal opinion is that ConsulClient should not be managing HttpClient lifetimes at all since they hide serious issues from the library user.

**Comment by maurosbarigia** [comment]
I don't really see any strong reasons to obsolete and remove those constructors. As discussed in a previous PR, we inherited them obsoleted, but I have nothing against unobsoleting them, leaving both options available.

**Comment by jgiannuzzi** [comment]
Thank you @Salgat for suggesting this improvement to Consul.NET!

And thank you @maurosbarigia for reviewing this 👍

Would someone want to contribute a PR to un-obsolete those constructors?

**Comment by Salgat** [comment]
If no one puts one up in the meantime I'll put up a PR when I get the chance. I want to make sure this gets in since my company is using this + IHttpClientFactory 😊.
