### ISSUE TITLE
Support for "/agent/health/service/*" API methods.

### ISSUE THREAD

**Issue by firerain-fd** [G-Research/consuldotnet#25]
Are there any plans to support this functionality https://www.consul.io/api-docs/agent/service#get-local-service-health ?

**Comment by mfkl** [comment]
Hi @firerain-fd,

Thanks for the interest. Would you like to contribute a PR to https://github.com/G-Research/consuldotnet/blob/master/Consul/Health.cs?

**Comment by firerain-fd** [comment]
No. I wonder if this functionality will be supported in future versions?

**Comment by firerain-fd** [comment]
Sorry, I got the wrong label.
This is not a bug but an enhancement.

**Comment by mfkl** [comment]
Yes, but I don't have the necessary rights to change it.

**Comment by jgiannuzzi** [comment]
Hi @firerain-fd, I confirm that we are currently not planning to support these methods in future versions.

However, PRs are always welcome, so if you know anyone who can help implement it, send them this way! 😄
