### ISSUE TITLE
Add possibility to filter service by multiple tags  

### ISSUE THREAD

**Issue by HAghajanyan-ST** [G-Research/consuldotnet#26]
[tag](https://www.consul.io/api-docs/catalog#tag) (string: "") - Specifies the tag to filter on. This is specified as part of the URL as a query parameter. **Can be used multiple times for additional filtering**, returning only the results that include all of the tag values provided.

**Comment by jgiannuzzi** [comment]
Hi @HAghajanyan-ST, thanks for suggesting this feature, it's a great idea!

Implementing it would require changing `ConsulRequest`, as its `Params` are implemented as a `Dictionary<string, string>`, which would not allow to specify tag multiple times.
Once changed, we could then have an additional `Catalog.Service` method accepting a list of tags.

Would you like to create a PR implementing this?

**Comment by HAghajanyan-ST** [comment]
Yes of course, I can create PR

**Comment by hovik-aghajanyan** [comment]
> Yes of course, I can create PR

For PR I will use my personal account :)

**Comment by jgiannuzzi** [comment]
Awesome, looking forward to it!

**Comment by jgiannuzzi** [comment]
Hi @hovik-aghajanyan, did you see my comments on #27?

Would you be able to create those new PRs to address this issue?

**Comment by HAghajanyan-ST** [comment]
Hi @jgiannuzzi , sorry for late response. Yes, I have already create PRs.

**Comment by janstadt** [comment]
Could you also add the ability to do this by `node-meta` as well? example: `v1/catalog/nodes?node-meta=promoted:False&node-meta=status:ready` would be very useful.  https://github.com/G-Research/consuldotnet/blob/6351664c2cf07c920cd360a831d0d66e4df85764/Consul/Catalog.cs#L34 also doesnt return any `Meta` information. That would also be great to get back.

**Comment by janstadt** [comment]
I ended up creating an extension method and a class that has a `Meta` property for this. Not the prettiest code but if anyone else needed something similar. Also, please let me know if there is a better api for this kind of querying.

```
public static class CatalogExtensions
    {
        public static Task<QueryResult<ConsulNode[]>> NodesWithMeta(this ConsulClient client, IDictionary<string, string> meta, QueryOptions q, CancellationToken ct = default(CancellationToken))
        {
            var queryParams = new List<string>();
            foreach (var queryParam in meta)
            {
                queryParams.Add($"node-meta={queryParam.Key}:{queryParam.Value}");
            }

            var parameters = string.Join("&", queryParams);

            return new GetRequest<ConsulNode[]>(client, $"/v1/catalog/nodes?{parameters}", q).Execute(ct);
        }
    }
```

**Comment by mfkl** [comment]
Please try https://www.nuget.org/packages/Consul/1.6.10.1-rc1
