### ISSUE TITLE
Add CI for Consul.AspNetCore

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/consuldotnet#29]
Now that we have our initial ASP.NET extensions project, we need to add support in our CI pipeline to build, test, and publish it.

**Comment by sergeyshaykhullin** [comment]
@jgiannuzzi Does CI for Consul.AspNetCore should be inside ci.yaml workflow or it has to be in a separate?

**Comment by sergeyshaykhullin** [comment]
@jgiannuzzi Draft version https://github.com/G-Research/consuldotnet/pull/38

**Comment by jgiannuzzi** [comment]
We are getting very close to releasing v1.0.0 of @sergeyshaykhullin's new Consul.AspNetCore library. Hang in there!

**Comment by mfkl** [comment]
https://github.com/G-Research/consuldotnet/blob/master/.github/workflows/consul.aspnetcore.yml
