### ISSUE TITLE
FEATURE REQUEST: List Services for Gateway

### ISSUE THREAD

**Issue by JocelynVelarde** [G-Research/consuldotnet#315]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add support to [List Services for Gateway](https://developer.hashicorp.com/consul/api-docs/v1.9.x/catalog#list-services-for-gateway) 
This endpoint returns the services associated with an ingress gateway or terminating gateway.
This API is supported in the Golang client ([1.9.17](https://github.com/hashicorp/consul/blob/4897b16abf192942d1e1d2ffa109bf17b2431e9a/api/catalog.go#L310))

### Describe alternatives you've considered

Nothing for the moment

### Additional context

Nothing for the moment

**Comment by IvanKolchanov** [comment]
Hi! My name is Ivan Kolchanov, I am a MLH fellow working on Consul.NET right now. I have been working on features to get Consul.NETup-to-date with 1.9.17. Just wanted to ask if you are going to finish GET Gateaway services any time soon? If you are busy and do not have time for the project now I can finish that endpoint. Thank you in advance!

**Comment by JocelynVelarde** [comment]
> Hi! My name is Ivan Kolchanov, I am a MLH fellow working on Consul.NET right now. I have been working on features to get Consul.NETup-to-date with 1.9.17. Just wanted to ask if you are going to finish GET Gateaway services any time soon? If you are busy and do not have time for the project now I can finish that endpoint. Thank you in advance!

Hello! Glad to see your contributions. Yes of course, you can go ahead and finish the issues. I believe this specific one, was almost ready to merge, there where just some unexpected errors. If you wish you can check the PR conversation to see what is done and what is there to fix.
