### ISSUE TITLE
[Bug]: Automated github build of consuldotnet broken

### ISSUE THREAD

**Issue by julie-mindcapers** [G-Research/consuldotnet#318]
### Describe the bug

I created a pull request for a markdown only change. The automated build is broken, pretty sure I didn't do it.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Could not find 'dotnet' host for the 'X64' architecture.

You can resolve the problem by installing the 'X64' .NET.

### Steps To Reproduce

1. Make a documentation only change
2. Commit
3. Make pull request

### Expected behavior

Automated build runs successfully.

### Environment

- OS:       
- Consul Version:   
- consultdotnet Version   

### Logs

https://github.com/G-Research/consuldotnet/pull/316

### Additional context

Automated build failed on pull request with only a documentation change.

**Comment by adamreeve** [comment]
Hi @julie-mindcapers, thanks for the bug report.

This is being fixed in #317.
