### ISSUE TITLE
FEATURE REQUEST: Update LAN Coordinates for a node

### ISSUE THREAD

**Issue by JocelynVelarde** [G-Research/consuldotnet#322]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Add support to [Update LAN Coordinates for a node](https://developer.hashicorp.com/consul/api-docs/v1.9.x/coordinate#update-lan-coordinates-for-a-node) 
This endpoint updates the LAN network coordinates for a node in a given datacenter.
This API is supported in the Golang client ([1.9.17](https://github.com/hashicorp/consul/blob/4897b16abf192942d1e1d2ffa109bf17b2431e9a/api/coordinate.go#L71))

### Describe alternatives you've considered

Nothing for the moment.

### Additional context

Nothing for the moment.

**Comment by IvanKolchanov** [comment]
Hi! My name is Ivan Kolchanov, I am a MLH fellow working on Consul.NET right now. I have been working on features to get Consul.NET up-to-date with 1.9.17. Just wanted to ask if you are going to finish GET Update LAN Coordinates any time soon? If you are busy and do not have time for the project now I can finish that endpoint. Thank you in advance!

**Comment by JocelynVelarde** [comment]
> Hi! My name is Ivan Kolchanov, I am a MLH fellow working on Consul.NET right now. I have been working on features to get Consul.NET up-to-date with 1.9.17. Just wanted to ask if you are going to finish GET Update LAN Coordinates any time soon? If you are busy and do not have time for the project now I can finish that endpoint. Thank you in advance!

Hello! This one is a PUT api endpoint, the issue is only opened but no work has been done in relation. You can work on this as well, let me know if you have any further questions, I'll be glad to help out.
