### ISSUE TITLE
Typo on front page

### ISSUE THREAD

**Issue by alexravenna** [G-Research/consuldotnet#357]
### Describe the bug

There is a typo in the supported API table on the front page https://consuldot.net/:

![image](https://github.com/user-attachments/assets/222b266f-6461-40e7-b243-15e58ea447e0)

I would've submitted a change for this myself but I couldn't find the code for the front page in this repo, only the documentation.

### Steps To Reproduce

Browse to https://consuldot.net/

### Expected behavior

"foce" should be "force"

### Environment

Microsoft Edge

**Comment by marcin-krystianc** [comment]
@alexravenna Thanks for noting this and opening the issue.
