### ISSUE TITLE
[Bug]: Breaking change related to CONSUL_HTTP_ADDR parsing

### ISSUE THREAD

**Issue by orange-puff** [G-Research/consuldotnet#394]
### Describe the bug

Before version [v1.7.14.4](https://github.com/G-Research/consuldotnet/releases/tag/v1.7.14.4) which was introduced with this commit https://github.com/G-Research/consuldotnet/commit/ef310c22d35684892bd2231a53f3e9bbf907c78a

If `CONSUL_HTTP_ADDR` was set to just an IP address, the default port of `8500` would be used
This is the commit right before the breaking commit to `Client.cs`
https://github.com/G-Research/consuldotnet/blob/f6a8038af144ffa3a8ebf8b05cb3181aad4c50f6/Consul/Client.cs#L162
shows this.

Now, if `CONSUL_HTTP_ADDR` is set to just an IP address, it will be parsed using the dotnet `Uri` class which will resolve no port to the default port `80`

The obvious solution from the consumer side is to change this environment variable. But, as I was looking into how many downstream things may break, I was wondering if we could introduce some mechanism to preserve the old behavior. Perhaps an environment variable (I do not care what the name is)
`CONSULDOTNET_HTTP_PORT`, which when specified, can override the uri parsed port. 

### Steps To Reproduce

1. `git checkout f6a8038`
2. run a test where `CONSUL_HTTP_ADDR=127.0.0.1`
3. See port resolve to `8500`
4. `git checkout ef310c2`
5. run the same test
6. See port resolve to `80`

### Expected behavior

default port 8500 is used when not specified in the `CONSUL_HTTP_ADDR` environment variable

### Environment

- OS:       
- Consul Version:   
- consultdotnet Version

**Comment by larrytamnjong** [comment]
Thanks for reporting this issue, @orange-puff! I'm currently looking into it.

**Comment by marcin-krystianc** [comment]
@orange-puff thanks for reporting the problem. We've published a version v1.7.14.5 with a fix. The upgrade process to the fixed version doesn't require any extra actions or steps apart from bumping the version.
