### ISSUE TITLE
Nuget push? 

### ISSUE THREAD

**Issue by kingjuk** [G-Research/consuldotnet#58]
You have a lot of great changes in the code. When do you plan to push your latest to nuget?

**Comment by jgiannuzzi** [comment]
Thanks for your interest in Consul.NET, @kingjuk!

We are planning to create a new release soon. We need to solve a few things with our CI first so that we can have proper testing of all the versions of Consul, .NET, and operating systems we want to support.

Thanks for your patience!

**Comment by mfkl** [comment]
@kingjuk please try https://www.nuget.org/packages/Consul/1.6.10.1-rc1

**Comment by jgiannuzzi** [comment]
We have now (finally) released [1.6.10.1](https://www.nuget.org/packages/Consul/1.6.10.1), so I will close this issue.

Thanks again for your patience!
