### ISSUE TITLE
Lock Acquire operation null reference exception + cancellation token not respected

### ISSUE THREAD

**Issue by georgy93** [G-Research/consuldotnet#65]
Hello!

Recently I've been playing with the distributed lock feature of Consul in an ASP Net Core 3.1 application.
I'm using the latest version of consuldotnet 1.6.1.1
I have a Background service that calls the Task<CancellationToken> Acquire(CancellationToken ct) continuously in a "block indefinitely" approach (LockTryOnce is left with its default value).  I.e. If I am not a leader, then wait until I am. If I was previously a leader, try become leader again in case I lost the leadership (e.g session invalidation). 

However, I have the following two issues :
- If I call Acquire method with an already cancelled token I get a Null Reference Exception from whitin the consul library. 
- If the lock is already held by another instace of my application and my current "slave" instance is in a blocked Acquire call, then when I perform a gracefull shutdown, my BackgroundService cancellaiton token is not respected although I'm passing it to the Acquire method. The Acqurie method still keeps the blocked operation until "LockWaitTime" has passed. Then I again get a Null Reference exception. 
What is even worse is that in order to have my gracefull shutdown complete normally for the entire application I must either increase the ASP Net Core Host ShutDownTimeout or have some custom extension method where I for example do:
"await Task.WhenAny(AcquireLockTask, TaskThatCompletesUpponCancellationTokenCancelled);"

Edit:
I've just done a quick debug session and I found that:
In the finally block of the Acquire method If I have never started a monitor task (e.g my application never acquried a lock, during its life) it will throw the null reference exception because:
 "await _monitorTask.ConfigureAwait(false);" will be "await null.ConfigureAwait(false)".
https://github.com/G-Research/consuldotnet/blob/master/Consul/Lock.cs#L357

 However adding an "if" to check if the task _monitorTask is initialised would lead to 
 "throw new LockNotHeldException("Unable to acquire the lock with Consul");" 
https://github.com/G-Research/consuldotnet/blob/master/Consul/Lock.cs#L345
because this was the last thing from the method before the finally block. I'm not sure if this exception would be correct in case of cancellation token being cancelled. Could be, could be not.

For the second issue where the CancellationToken is not respected:
https://github.com/G-Research/consuldotnet/blob/master/Consul/Lock.cs#L278 
https://github.com/G-Research/consuldotnet/blob/master/Consul/Lock.cs#L330
This query "await _client.KV.Get(Opts.Key, qOpts).ConfigureAwait(false);" blocks for the amout of time set for LockWaitTime.
Can you please explain why the cancellation token is not passed?

**Comment by mfkl** [comment]
Hi,

Thanks for the report! So we can best assist you, could you please follow the [issue template](https://raw.githubusercontent.com/G-Research/consuldotnet/master/.github/ISSUE_TEMPLATE/bug_report.md) with your info? Thanks!

> If I call Acquire method with an already cancelled token I get a Null Reference Exception from whitin the consul library.

This would be a bug. Feel free to share a repro code (or unit test) :-)

> Can you please explain why the cancellation token is not passed?

No reason, it may have been overlooked. Could you share a repro/unit test for this as well please?

Thanks.

**Comment by georgy93** [comment]
Hi again!
Thank you for your response!
Here are the unit tests. Please note, that if you run them all at once, one might fail because the lock entry doesn't clean up always from consul agent. However, if you make sure there is no lock session before each test runs they all pass.

Consuldotnet v 1.6.1.1
OS: Windows

namespace XUnitTestProject1
{
    using Consul;
    using System;
    using System.Diagnostics;
    using System.Threading;
    using System.Threading.Tasks;
    using Xunit;
    public class LockTest
    {
        private readonly string key = "service/myApp/leader";
        private readonly Uri _uri = new Uri("http://consul:8500");
        private readonly LockOptions _lockOptions;
        private readonly ConsulClient _slaveInstanceClient;
        private readonly ConsulClient _masterInstanceClient;
        private const int DefaultSessionTTLSeconds = 10;
        private const int LockWaitTimeSeconds = 15;
        public LockTest()
        {
            _lockOptions = new LockOptions(key)
            {
                SessionTTL = TimeSpan.FromSeconds(DefaultSessionTTLSeconds),
                LockWaitTime = TimeSpan.FromSeconds(LockWaitTimeSeconds)
            };
            _slaveInstanceClient = new ConsulClient(c => c.Address = _uri);
            _masterInstanceClient = new ConsulClient(c => c.Address = _uri);
        }
        [Fact]
        public async Task Passing_Cancelled_CancellationToken_Throws_NullReferenceEx()
        {
            // Arrange
            var distributedLock = _slaveInstanceClient.CreateLock(_lockOptions);
            var cts = new CancellationTokenSource();
            // Act
            cts.Cancel();
            // Assert
            await Assert.ThrowsAsync<NullReferenceException>(async () =>
                await distributedLock.Acquire(cts.Token));
        }
        [Fact]
        public async Task Cancelling_A_Token_When_Acquiring_A_Lock_Throws_NullReferenceEx()
        {
            // Arrange
            var distributedLock2 = _masterInstanceClient.CreateLock(_lockOptions);
            var distributedLock = _slaveInstanceClient.CreateLock(_lockOptions);
            var cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
            // Act
            await distributedLock2.Acquire(); // Become "Master" with another instance first
            var task = distributedLock.Acquire(cts.Token);
            // Assert
            await Assert.ThrowsAsync<NullReferenceException>(async () => await task);
            // cleanup
            await distributedLock2.Release();
            if (distributedLock.IsHeld)
                await distributedLock2.Release();
            await distributedLock2.Destroy();
        }
        [Fact]
        public async Task Cancelling_A_Token_When_Acquiring_A_Lock_Doesnt_Respect_Token()
        {
            // Arrange
            var distributedLock2 = _masterInstanceClient.CreateLock(_lockOptions);
            var distributedLock = _slaveInstanceClient.CreateLock(_lockOptions);
            var cancellationOperationTimer = new Stopwatch();
            var cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
            // Act
            await distributedLock2.Acquire(); // Become "Master" with another instance first
            cancellationOperationTimer.Start();
            try
            {
                await distributedLock.Acquire(cts.Token);
            }
            catch (Exception) { }
            cancellationOperationTimer.Stop();
            // Assert
            var stopTimeMs = cancellationOperationTimer.ElapsedMilliseconds;
            var LockWaitTimeMs = TimeSpan.FromSeconds(LockWaitTimeSeconds).TotalMilliseconds;
            Assert.True(stopTimeMs > LockWaitTimeMs);
            // cleanup
            await distributedLock2.Release();
            if (distributedLock.IsHeld)
                await distributedLock2.Release();
            await distributedLock2.Destroy();
        }
    }
}

**Comment by mfkl** [comment]
Great, thanks. 

Would you mind pushing them to a branch on your fork and sharing it here, please? This will be easier to retrieve and run locally for the maintainers :-)

**Comment by mfkl** [comment]
Please try https://www.nuget.org/packages/Consul/1.6.10.1-rc1

**Comment by georgy93** [comment]
Hi, Today I updated to the latest version of the package and the issues are resolved. Thanks!
