### ISSUE TITLE
the result of query service need more than one second

### ISSUE THREAD

**Issue by Smartearth** [G-Research/consuldotnet#90]
**Describe the bug**

I query the service result by consulClient,
this spend more than one second

**Steps To Reproduce**

**Expected behavior**

**Logs**

**Environment**

- OS:       windows 10
- Consul Version:   1.6.10.1
- consultdotnet Version   5.0

**Additional context**

var query = consulClient.Health.Service(serviceName);
var entryArray = query.Result.Response; // more than one second here

**Comment by mfkl** [comment]
Hi,

I'm not sure I'm following... what do you think is the problem here? Could you point to the code you think is wrong?

Is your internet connection slow?

**Comment by Smartearth** [comment]
I query the regiested service by consul client, returns the result takes about one second.
It is localhost

I query the regersted service by url("http://127.0.0.1:8500/v1/health/service/servicename?passing=true"), the result returns rapidly

**Comment by Smartearth** [comment]
consul V1.5.2 is working properly

**Comment by mfkl** [comment]
Could you please share minimal repro code sample? That'd help us to confirm it quickly, if that's a regression.

**Comment by Smartearth** [comment]
var query = consulClient.Health.Service(serviceName);
var entryArray = query.Result.Response; // more than one second here

the key code

**Comment by mfkl** [comment]
Please read https://stackoverflow.com/help/minimal-reproducible-example and provide a minimal sample in a git repro, including with timing measurements to support your claim.

**Comment by marcin-krystianc** [comment]
@Smartearth Can you double check whether you still reproduce the problem ?
I've tried it locally with this modified test case:
```
        [Fact]
        public async Task Health_GetConsulService()
        {
            while (true)
            {
                var sw = Stopwatch.StartNew();
                var checks = await _client.Health.Service("consul");
                File.AppendAllText("d:/log.txt", sw.Elapsed + Environment.NewLine);
                Assert.NotEqual((ulong)0, checks.LastIndex);
                Assert.NotEmpty(checks.Response);
            }
        }
```
and the query completes within few milliseconds.

**Comment by Smartearth** [comment]
the enviroment is consul V1.5.2,
it works nice
it is inconvenience to comparison test

**Comment by mfkl** [comment]
Closing this per lack of info.

Feel free to re-open with a minimal repro sample and exact steps if this is still an issue for you.

Thanks
